import { DeliverableRow, Creator, DeliverableBundle } from '../types/campaign';

export const mockCreators: Creator[] = [
  {
    id: '1',
    name: '@fashionista_jane',
    tier: 'macro',
    followers: 250000,
    engagementRate: 4.2,
    baseRate: 2500,
  },
  {
    id: '2',
    name: '@fitness_guru_mike',
    tier: 'mid',
    followers: 75000,
    engagementRate: 6.1,
    baseRate: 1200,
  },
  {
    id: '3',
    name: '@beauty_blogger_sarah',
    tier: 'micro',
    followers: 25000,
    engagementRate: 8.3,
    baseRate: 500,
  },
  {
    id: '4',
    name: '@lifestyle_emma',
    tier: 'nano',
    followers: 5000,
    engagementRate: 12.5,
    baseRate: 150,
    isArchetype: true,
  },
  {
    id: '5',
    name: '@tech_reviewer_alex',
    tier: 'macro',
    followers: 500000,
    engagementRate: 3.8,
    baseRate: 4000,
  },
];

export const platformDeliverables = {
  instagram: ['Post', 'Story', 'Reel', 'IGTV', 'Carousel'],
  tiktok: ['Video', 'Live Stream', 'Spark Ad'],
  youtube: ['Video', 'Short', 'Community Post', 'Live Stream'],
  twitter: ['Tweet', 'Thread', 'Space', 'Video'],
};

export const cohortTypes = [
  { 
    id: 'nano', 
    name: 'Nano Influencers (1K-10K)', 
    baseRate: 100,
    subTiers: [
      { id: 'nano-1', name: 'Nano Tier 1 (1K-2.5K)', baseRate: 75 },
      { id: 'nano-2', name: 'Nano Tier 2 (2.5K-5K)', baseRate: 100 },
      { id: 'nano-3', name: 'Nano Tier 3 (5K-10K)', baseRate: 150 },
    ]
  },
  { 
    id: 'micro', 
    name: 'Micro Influencers (10K-100K)', 
    baseRate: 500,
    subTiers: [
      { id: 'micro-1', name: 'Micro Tier 1 (10K-25K)', baseRate: 350 },
      { id: 'micro-2', name: 'Micro Tier 2 (25K-50K)', baseRate: 500 },
      { id: 'micro-3', name: 'Micro Tier 3 (50K-100K)', baseRate: 750 },
    ]
  },
  { 
    id: 'mid', 
    name: 'Mid-Tier Influencers (100K-1M)', 
    baseRate: 1500,
    subTiers: [
      { id: 'mid-1', name: 'Mid Tier 1 (100K-250K)', baseRate: 1200 },
      { id: 'mid-2', name: 'Mid Tier 2 (250K-500K)', baseRate: 1500 },
      { id: 'mid-3', name: 'Mid Tier 3 (500K-1M)', baseRate: 2000 },
    ]
  },
  { 
    id: 'macro', 
    name: 'Macro Influencers (1M+)', 
    baseRate: 5000,
    subTiers: [
      { id: 'macro-1', name: 'Macro Tier 1 (1M-2.5M)', baseRate: 4000 },
      { id: 'macro-2', name: 'Macro Tier 2 (2.5M-5M)', baseRate: 6000 },
      { id: 'macro-3', name: 'Macro Tier 3 (5M+)', baseRate: 10000 },
    ]
  },
];

export const deliverableBundles: DeliverableBundle[] = [
  {
    id: 'ig-standard',
    name: 'Instagram Standard',
    platform: 'instagram',
    deliverables: [
      { type: 'Post', quantity: 1, multiplier: 1.0 },
      { type: 'Story', quantity: 2, multiplier: 0.5 },
    ],
    description: '1 Post + 2 Stories',
  },
  {
    id: 'ig-premium',
    name: 'Instagram Premium',
    platform: 'instagram',
    deliverables: [
      { type: 'Reel', quantity: 1, multiplier: 1.5 },
      { type: 'Post', quantity: 1, multiplier: 1.0 },
      { type: 'Story', quantity: 3, multiplier: 0.5 },
    ],
    description: '1 Reel + 1 Post + 3 Stories',
  },
  {
    id: 'tiktok-viral',
    name: 'TikTok Viral Package',
    platform: 'tiktok',
    deliverables: [
      { type: 'Video', quantity: 2, multiplier: 1.0 },
      { type: 'Live Stream', quantity: 1, multiplier: 0.8 },
    ],
    description: '2 Videos + 1 Live Stream',
  },
];

export const createMockDeliverable = (overrides: Partial<DeliverableRow> = {}): DeliverableRow => ({
  id: crypto.randomUUID(),
  type: 'organic',
  platform: 'instagram',
  deliverableType: 'Post',
  creatorType: 'cohort',
  creatorInfo: 'Micro Influencers (10K-100K)',
  cohortSize: 5,
  quantity: 1,
  unitFee: 500,
  baseRate: 500,
  rights: {
    usage: 'organic',
    duration: 6,
    territory: 'domestic',
    exclusivity: false,
    competitorCount: 0,
    multiplier: 1.0,
  },
  estimatedViews: 25000,
  estimatedEngagements: 2000,
  children: [],
  bulkSelected: false,
  needsApproval: false,
  ...overrides,
});

export const sampleDeliverables: DeliverableRow[] = [
  {
    ...createMockDeliverable({
      platform: 'instagram',
      deliverableType: 'Post',
      creatorInfo: 'Micro Influencers (10K-100K)',
      cohortSize: 5,
      quantity: 1,
      unitFee: 500,
      estimatedViews: 25000,
      estimatedEngagements: 2000,
    }),
    children: [
      createMockDeliverable({
        type: 'paid',
        parentId: 'parent1',
        platform: 'instagram',
        deliverableType: 'Boosted Post',
        creatorInfo: 'Micro Influencers (10K-100K)',
        cohortSize: 5,
        quantity: 1,
        unitFee: 200,
        rights: {
          usage: 'paid',
          duration: 3,
          territory: 'domestic',
          exclusivity: false,
          competitorCount: 0,
          multiplier: 1.5,
        },
        estimatedViews: 50000,
        estimatedEngagements: 3000,
      }),
    ],
  },
  createMockDeliverable({
    platform: 'tiktok',
    deliverableType: 'Video',
    creatorType: 'specific',
    creatorInfo: mockCreators[0], // @fashionista_jane
    cohortSize: undefined,
    quantity: 2,
    unitFee: 2500,
    estimatedViews: 500000,
    estimatedEngagements: 45000,
    rights: {
      usage: 'both',
      duration: 12,
      territory: 'global',
      exclusivity: true,
      competitorCount: 2,
      multiplier: 2.5,
    },
  }),
  createMockDeliverable({
    platform: 'youtube',
    deliverableType: 'Video',
    creatorType: 'archetype',
    creatorInfo: 'Tech Reviewers (Similar to @tech_reviewer_alex)',
    cohortSize: 3,
    quantity: 1,
    unitFee: 3000,
    estimatedViews: 200000,
    estimatedEngagements: 15000,
    rights: {
      usage: 'organic',
      duration: 6,
      territory: 'domestic',
      exclusivity: false,
      competitorCount: 0,
      multiplier: 1.0,
    },
  }),
];

export const sampleCampaigns: Campaign[] = [
  {
    id: 'campaign-1',
    name: 'Holiday Push Q4',
    client: 'Shea',
    brand: 'Shea Butter Collection',
    markets: ['US', 'CA'],
    currency: 'USD',
    primaryObjective: 'awareness',
    primaryKpis: ['Reach', 'Impressions', 'Engagements'],
    secondaryKpis: ['Brand Lift'],
    startDate: new Date('2024-10-15'),
    endDate: new Date('2024-12-31'),
    duration: 77,
    budgetType: 'campaign',
    budgetAmount: 650000,
    industryTags: ['Beauty & Personal Care'],
    contentThemes: ['Holiday', 'Product Launch'],
    legalRightsPreset: 'both',
    deliverables: [
      createMockDeliverable({
        platform: 'instagram',
        deliverableType: 'Reel',
        creatorInfo: 'Macro Influencers (1M+)',
        cohortSize: 15,
        quantity: 2,
        unitFee: 8000,
        estimatedViews: 2000000,
        estimatedEngagements: 180000,
        rights: {
          usage: 'both',
          duration: 12,
          territory: 'domestic',
          exclusivity: true,
          competitorCount: 2,
          multiplier: 2.2,
        },
      }),
      createMockDeliverable({
        platform: 'tiktok',
        deliverableType: 'Video',
        creatorInfo: 'Mid-Tier Influencers (100K-1M)',
        cohortSize: 25,
        quantity: 3,
        unitFee: 2500,
        estimatedViews: 800000,
        estimatedEngagements: 64000,
      }),
      createMockDeliverable({
        platform: 'youtube',
        deliverableType: 'Short',
        creatorInfo: 'Micro Influencers (10K-100K)',
        cohortSize: 30,
        quantity: 1,
        unitFee: 400,
        estimatedViews: 150000,
        estimatedEngagements: 12000,
        rights: {
          usage: 'organic',
          duration: 6,
          territory: 'domestic',
          exclusivity: false,
          competitorCount: 0,
          multiplier: 1.0,
        },
      }),
    ],
    planningMode: 'blended',
    setupProgress: 6,
    performanceScore: 82,
    performanceLabel: 'On track',
    rightsStatus: 'ok',
    expiringRightsCount: 2,
    overBudget: false,
    underPacing: false,
    pacingPercentage: 5,
    commentsCount: 8,
    filesCount: 12,
    lastEditedBy: 'Sarah Johnson',
    lastEditedAt: new Date('2024-12-15T14:30:00'),
    category: 'Holiday Campaign',
    leadAvatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    teamAvatars: [
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    ],
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'campaign-2',
    name: 'Spring Lifestyle',
    client: 'Holiday',
    brand: 'Spring Collection',
    markets: ['UK', 'FR', 'DE'],
    currency: 'GBP',
    primaryObjective: 'relevance',
    primaryKpis: ['Brand Lift', 'Purchase Intent'],
    secondaryKpis: ['Engagements', 'Website Traffic'],
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-05-31'),
    duration: 91,
    budgetType: 'campaign',
    budgetAmount: 180000,
    industryTags: ['Fashion'],
    contentThemes: ['Seasonal', 'User-Generated Content'],
    legalRightsPreset: 'organic',
    deliverables: [
      createMockDeliverable({
        platform: 'instagram',
        deliverableType: 'Post',
        creatorInfo: 'Micro Influencers (10K-100K)',
        cohortSize: 20,
        quantity: 1,
        unitFee: 1200,
        estimatedViews: 400000,
        estimatedEngagements: 32000,
      }),
      createMockDeliverable({
        platform: 'tiktok',
        deliverableType: 'Video',
        creatorInfo: 'Nano Influencers (1K-10K)',
        cohortSize: 50,
        quantity: 2,
        unitFee: 150,
        estimatedViews: 75000,
        estimatedEngagements: 9000,
        rights: {
          usage: 'organic',
          duration: 3,
          territory: 'domestic',
          exclusivity: false,
          competitorCount: 0,
          multiplier: 1.0,
        },
      }),
    ],
    planningMode: 'generic',
    setupProgress: 3,
    performanceScore: 0,
    performanceLabel: 'Draft',
    rightsStatus: 'attention',
    missingRightsCount: 3,
    overBudget: false,
    underPacing: false,
    commentsCount: 2,
    filesCount: 1,
    lastEditedBy: 'Mike Chen',
    lastEditedAt: new Date('2024-12-10T09:15:00'),
    category: 'Seasonal',
    leadAvatar: 'https://images.pexels.com/photos/1181424/pexels-photo-1181424.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    teamAvatars: [
      'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    ],
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 'campaign-3',
    name: 'Terre de Lumière',
    client: 'Lumier',
    brand: 'Terre de Lumière',
    markets: ['US', 'CA', 'UK'],
    currency: 'USD',
    primaryObjective: 'sales',
    primaryKpis: ['Conversions', 'Sales Revenue', 'Return on Ad Spend'],
    secondaryKpis: ['Clicks', 'Website Traffic'],
    startDate: new Date('2024-11-01'),
    endDate: new Date('2024-12-31'),
    duration: 60,
    budgetType: 'campaign',
    budgetAmount: 65000,
    industryTags: ['Beauty & Personal Care'],
    contentThemes: ['Product Launch', 'Educational'],
    legalRightsPreset: 'both',
    deliverables: [
      createMockDeliverable({
        platform: 'youtube',
        deliverableType: 'Video',
        creatorInfo: 'Mid-Tier Influencers (100K-1M)',
        cohortSize: 8,
        quantity: 1,
        unitFee: 3500,
        estimatedViews: 600000,
        estimatedEngagements: 42000,
        rights: {
          usage: 'both',
          duration: 6,
          territory: 'global',
          exclusivity: false,
          competitorCount: 0,
          multiplier: 1.8,
        },
      }),
      createMockDeliverable({
        platform: 'instagram',
        deliverableType: 'Story',
        creatorType: 'specific',
        creatorInfo: mockCreators[1], // @fitness_guru_mike
        cohortSize: undefined,
        quantity: 5,
        unitFee: 300,
        estimatedViews: 50000,
        estimatedEngagements: 4000,
        rights: {
          usage: 'organic',
          duration: 3,
          territory: 'domestic',
          exclusivity: false,
          competitorCount: 0,
          multiplier: 1.0,
        },
      }),
    ],
    planningMode: 'specific',
    setupProgress: 6,
    performanceScore: 74,
    performanceLabel: 'Good',
    rightsStatus: 'ok',
    expiringRightsCount: 0,
    overBudget: false,
    underPacing: true,
    pacingPercentage: -8,
    commentsCount: 5,
    filesCount: 3,
    lastEditedBy: 'Emma Rodriguez',
    lastEditedAt: new Date('2024-12-14T16:45:00'),
    category: 'Beauty Launch',
    leadAvatar: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    teamAvatars: [
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    ],
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-12-14'),
  },
  // Additional campaign for more variety
  {
    id: 'campaign-4',
    name: 'Summer Fitness Challenge',
    client: 'FitLife',
    brand: 'ActiveWear Pro',
    markets: ['US', 'CA', 'AU'],
    currency: 'USD',
    primaryObjective: 'traffic',
    primaryKpis: ['Website Traffic', 'Clicks', 'Engagements'],
    secondaryKpis: ['Conversions', 'Brand Lift'],
    startDate: new Date('2025-06-01'),
    endDate: new Date('2025-08-31'),
    duration: 91,
    budgetType: 'campaign',
    budgetAmount: 125000,
    industryTags: ['Sports', 'Fashion'],
    contentThemes: ['Seasonal', 'User-Generated Content'],
    legalRightsPreset: 'organic',
    deliverables: [
      createMockDeliverable({
        platform: 'instagram',
        deliverableType: 'Reel',
        creatorType: 'archetype',
        creatorInfo: 'Fitness Influencers (Similar to @fitness_guru_mike)',
        cohortSize: 12,
        quantity: 3,
        unitFee: 1800,
        estimatedViews: 360000,
        estimatedEngagements: 28800,
        rights: {
          usage: 'organic',
          duration: 6,
          territory: 'domestic',
          exclusivity: false,
          competitorCount: 0,
          multiplier: 1.0,
        },
      }),
      createMockDeliverable({
        platform: 'tiktok',
        deliverableType: 'Video',
        creatorInfo: 'Mid-Tier Influencers (100K-1M)',
        cohortSize: 8,
        quantity: 2,
        unitFee: 2200,
        estimatedViews: 640000,
        estimatedEngagements: 51200,
        rights: {
          usage: 'both',
          duration: 9,
          territory: 'global',
          exclusivity: true,
          competitorCount: 1,
          multiplier: 1.8,
        },
      }),
    ],
    planningMode: 'blended',
    setupProgress: 6,
    performanceScore: 68,
    performanceLabel: 'Good',
    rightsStatus: 'ok',
    expiringRightsCount: 0,
    overBudget: false,
    underPacing: false,
    pacingPercentage: 2,
    complianceConflicts: false,
    blocked: false,
    commentsCount: 3,
    filesCount: 7,
    lastEditedBy: 'Alex Thompson',
    lastEditedAt: new Date('2024-12-12T11:20:00'),
    category: 'Fitness Campaign',
    leadAvatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    teamAvatars: [
      'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      'https://images.pexels.com/photos/1181424/pexels-photo-1181424.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
    ],
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-12-12'),
  },
];